import learnLingo from "/public/images/learn_lingo.jpg";
import carRental from "/public/images/car_rental.jpg";
import movieSearch from "/public/images/main_page_movies_app.jpg";
import contactsApp from "/public/images/main_page_contacts.jpg";
import webStudio from "/public/images/lending.jpg";
import restaurantTestTask from "/public/images/restaurant_test_task.jpg";
import contactsTestTask from "/public/images/contacts-test-task.jpg";
import myportfolio from "/public/images/myportfolio.jpg";
import frontendTestTask from "/public/images/test_task.webp";
import restAPI from "/public/images/rest_api.webp";

export const personalProjects = [
  {
    id: 3,
    href: "https://portfolio-by-ivan-malakhovskyi.vercel.app/en",
    git: "https://github.com/Ivan-Malakhovskyi/portfolio-by-ivan-malakhovskyi",
    title: "Portfolio",
    description: "Self presentation",
    img: myportfolio,
    role: null,
    workedOn: null,
    technologies: [
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "Google SEO",
      "Internationalization",
    ],
    toDo: null,
  },
  {
    id: 4,
    href: "https://learn-lingo-pet-project.vercel.app/",
    git: "https://github.com/Ivan-Malakhovskyi/learn-lingo-pet-project",
    title: "Learn Lingo",
    description: "Online language learning services",
    img: learnLingo,
    role: null,
    workedOn: null,
    technologies: [
      "React",
      "TS",
      "Vite",
      "React-dom",
      "Redux",
      "Firebase",
      "Filtering teachers by languages, level, price",
      "Add/remove teachers to favorites",
    ],
    toDo: null,
  },
  {
    id: 5,
    href: "https://ivan-malakhovskyi.github.io/test-project-rental-car/",
    git: "https://github.com/Ivan-Malakhovskyi/test-project-rental-car",
    title: "Rental Car",
    description: "The Rental Car service",
    img: carRental,
    role: null,
    workedOn: null,
    technologies: ["React", "Redux", "React-router"],
    toDo: null,
  },
  {
    id: 6,
    href: "https://ivan-malakhovskyi.github.io/react-router-movies/",
    git: "https://github.com/Ivan-Malakhovskyi/react-router-movies",
    title: "Movie Search",
    description: "The Movie Search service",
    img: movieSearch,
    role: null,
    workedOn: null,
    technologies: [
      "React",
      "React-router-dom",
      "React Hooks",
      "Http Abort",
      "styled-components",
    ],
    toDo: null,
  },
  {
    id: 7,
    href: "https://ivan-malakhovskyi.github.io/signup-signin-redux",
    git: "https://github.com/Ivan-Malakhovskyi/signup-signin-redux",
    title: "Contacts",
    description: "The Contacts App service",
    img: contactsApp,
    role: null,
    workedOn: null,
    technologies: [
      "React",
      "Redux",
      "Authentication",
      "React-router-dom",
      "React Hooks",
      "Http Abort",
      "styled-components",
      "Operations with contacts",
    ],
    toDo: null,
  },
  {
    id: 8,
    href: "https://ivan-malakhovskyi.github.io/adaptive-layout-graphics/",
    git: "https://github.com/Ivan-Malakhovskyi/adaptive-layout-graphics",
    title: "Web Studio",
    description: "The Web Studio landing",
    img: webStudio,
    role: null,
    workedOn: null,
    technologies: ["HTML/CSS/JS", "Sass", "Responsive design"],
    toDo: null,
  },
  {
    id: 9,
    href: "https://restaurant-test-task.vercel.app/",
    git: "https://github.com/Ivan-Malakhovskyi/restaurant-test-task",
    img: restaurantTestTask,
    title: "Restaurant",
    description: "The Restaurant test task",
    role: null,
    workedOn: null,
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Responsive design",
    ],
    toDo: null,
  },
  {
    id: 10,
    href: "https://main--contacts-test-task.netlify.app/",
    git: "https://github.com/Ivan-Malakhovskyi/contacts-test-task",
    img: contactsTestTask,
    title: "Contacts",
    description: "Contacts test task",
    role: null,
    workedOn: null,
    technologies: [
      "React",
      "Vite",
      "styled-components",
      "react-router",
      "Responsive design",
    ],
    toDo: null,
  },
  {
    id: 11,
    href: "https://ivan-malakhovskyi.github.io/frontend-test-task/",
    git: "https://github.com/Ivan-Malakhovskyi/frontend-test-task",
    img: frontendTestTask,
    title: "Sales Fortuna",
    description: "Slider",
    role: null,
    workedOn: null,
    technologies: ["JS", "Sass", "Swiper.js", "Responsive design", "Vite"],
    toDo: null,
  },
  {
    id: 12,
    href: "https://contacts-service-v-2.onrender.com/api-docs/",
    git: "https://github.com/Ivan-Malakhovskyi/contacts_rest_api",
    img: restAPI,
    title: "API Contacts",
    description: "API Docs",
    role: null,
    workedOn: null,
    technologies: [
      "TypeScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Docker",
      "Swagger",
    ],
    toDo: null,
  },
];
